ALGORITHM:
  NAME: "FixMatchABC"
  CONFIDENCE_THRESHOLD: -5.0

MODEL:
  LOSS:
    UNLABELED_LOSS: "CrossEntropyLoss"
    UNLABELED_LOSS_WEIGHT: 1.0

DATASET:
  BUILDER: "build_cifar10_dataset"
  NAME: "cifar10"
  ROOT: "./data/cifar10"
  NUM_VALID: 5000
  CIFAR10:
    NUM_LABELED_HEAD: 500
    IMB_FACTOR_L: 150
    NUM_UNLABELED_HEAD: 4000
    IMB_FACTOR_UL: 150
  REVERSE_UL_DISTRIBUTION: False

  TRANSFORM:
    STRONG_AUG: True

SOLVER:
  UNLABELED_BATCH_RATIO: 2

OUTPUT_DIR: "outputs/cifar10/inpl"
